name: Build LaTeX Document
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV.tex
        
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: "Latest CV"
          tag: "Latest CV"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
