name: Build LaTeX Document
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV.tex
        
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: CV.pdf
          
      - name: 'Unzip project'
        uses: montudor/action-zip@v1.0.0
        with:
         args: unzip ${{ runner.temp }}/PDF.zip -d ${{ github.workspace }}
      
      - name: GIT commit and push PDF
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add CV.pdf
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
